language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - DEPOPTS="*"
    - TESTS=true
  matrix:
    - OCAML_VERSION=4.06
